spring:
    application:
        name: NutriBem
    datasource:
        url: jdbc:h2:mem:user
        username: sa
        password: 1234
        hibernate: 
            ddl-auto: uptade
    jpa: 
        database-platform: org.hibernate.dialect.H2Dialect  
    h2: 
        console: 
            enabled: true
